### ISSUE TITLE
Require Support

### ISSUE THREAD

**Issue by dhkatz** [dhkatz/gulp-ts-alias#17]
At the moment this plugin only supports new import style module imports. This could probably be relatively easily adapted to support `require()` imports as well. 

I personally never use them much, unless I'm requiring a third party module. This makes the need for path resolution in require less useful, because I'd never make any of my own modules need to be used with `require()`.

If anyone finds they need path resolution for this, let me know so I can work on it.

**Comment by DoctorJew** [comment]
I've begun work on support for modules using `require()`.

Just using two regex patterns instead of one:

https://github.com/dhkatz/gulp-ts-alias/blob/842b95bc3d13a86594d456bc69ffdd86941f94d9/src/index.ts#L50-L52

**Comment by dhkatz** [comment]
added in #60
