### ISSUE TITLE
Still tries to resolve path even for commented code

### ISSUE THREAD

**Issue by JamesParkDev** [dhkatz/gulp-ts-alias#193]
Example

```javascript
// let ex;

// try {
// 	ex = require("example");
// } catch (err) {
// 	ex = require("example1");
// }
```

This is fine to cause `Multiple imports on the same line are currently not supported!` But it should not try to resolve path if code was commented.

**Comment by JamesParkDev** [comment]
Was this fixed?

**Comment by dhkatz** [comment]
I took a bit of a naive approach but should be fixed for most cases yes
