### ISSUE TITLE
Dynamic Import Support

### ISSUE THREAD

**Issue by Eoyo** [dhkatz/gulp-ts-alias#52]
what about change `matches` in findImport function to:
```ts
const matches = line.match(/from (["'])(.*?)\1/) || line.match(/import\((["'])(.*?)\1\)/);
```

so,  we can do some thing like this:
```ts
import("src/test").then(test => test());
```

**Comment by dhkatz** [comment]
That is not how the match function works, but yes I will get on implementing support for that style of import.

**Comment by dhkatz** [comment]
Added in #60
